add distributor contract + interfaces
NexusMutual/distributor-contract pull request #2
Opened 2020-04-06 18:46 UTC by roxdanila

As I am making updates here I am also still updating the tests and cross-checking here:

https://github.com/NexusMutual/smart-contracts/compare/master...danoctavian:distributor-contract

For the test. Currently i'm just pulling in the bytecode from build directory of this repo and using that to deploy to them to the chain. what we can do is actually import the distributor contract, deploy and test against it for integration tests.

2020-04-20 06:21 UTC, danoctavian commented on contracts/NXMClient.sol
> +        uint[] memory coverDetails,
https://github.com/NexusMutual/distributor-contract/pull/2#discussion_r407326167

I discussed that there with @roxdanila  as well. the issue here is the "stack too deep" error.

The correct solution here is to use a struct but that needs passing a struct parameter in memory with requires the pragma experimental ABIEncoderV2  (which is not for production use in 0.5.* solidity).

The second best solution in terms of interface seems to be expanding this to 11 parameters, however this gets us too close to the max of 16 variables limit which is applied at compile time.

Example: if the written code needs to access variables variables at a depth more than 16 on the stack the compiler fails. For example the DUP instruction has DUP1, DUP2.. DUP16 to duplicate elements from the stack, but it stops at 16.

2020-12-22 12:38 UTC, shark0der requested changes

2020-12-22 12:38 UTC, shark0der commented on contracts/Distributor.sol
> +  mapping(address => uint) public withdrawableTokens;
Idea: use a treasury/wallet account and send funds to it directly instead of keeping them in this contract. The owner can change it at any time and can set it to be a multisig. In case of a hypotethical attack on the distributor attack the funds will be safe as they're not in the contract anymore. Implementing this renders `withdrawTokens` and `withdrawEther` useless. `sellNXM` should send the ether to the treasury as well, right after selling the nxm.

2020-12-22 12:38 UTC, shark0der commented on contracts/Distributor.sol
> +  }
Move this after the storage variables, before the constructor.

2020-12-22 12:38 UTC, shark0der commented on contracts/Distributor.sol
> +  Ownable,
Is Ownable's constructor automatically called and owner set?

2020-12-22 12:38 UTC, shark0der commented on contracts/Distributor.sol
> +  mapping (uint => Token) public tokens;
Maybe it would be better to rename this to `tokenDetails`? The tokens themselves are located in `ERC721`, not here. A public `tokens` getter will be confusing in this case.

2020-12-22 12:38 UTC, shark0der commented on contracts/Distributor.sol
> +    ) = cover.getCover(tokenId);
If we'd store the asset in `tokens`, we could use it here. I'm thinking since we only need payout here, how about writing a function that only returns that? Will be **much** cheaper in terms of gas.

2020-12-22 12:38 UTC, shark0der commented on contracts/Distributor.sol
> +  }
As I understand, this function's only purpose is to allow the owner to withdraw the NXM. Why not create an `withdrawNXM` function instead? Will result in a single tx instead of two. I believe this has been discussed so correct me if there's something I'm missing.

2020-12-22 12:38 UTC, shark0der commented on contracts/Distributor.sol
> +    pool = IPool(poolAddress);
This can change. I think we have to pass the master contract and read it on every call.

2020-12-22 12:38 UTC, shark0der commented on contracts/Distributor.sol
> +  IERC20 nxmToken;
Make `cover` and `nxmToken` immutable to save gas.

2020-12-22 12:38 UTC, shark0der commented on contracts/DistributorFactory.sol
> +        Distributor d = new Distributor(
Pass NFT token symbol and name here as well

2020-12-22 12:38 UTC, shark0der commented on contracts/DistributorFactory.sol
> +            master.getLatestAddress("P1"),
Pass the master instead of the pool. `Token` and and `Cover` should remain as they are.

2020-12-22 12:38 UTC, shark0der commented on contracts/DistributorFactory.sol
> +        return address(d);
I think the return is redundant. I doubt someone will use because if they're calling this programmatically they will probably deploy their own distributor contract instead.

2020-12-22 12:38 UTC, shark0der commented on contracts/interfaces/IPool.sol
> +    function sellNXMTokens(uint tokenAmount) external;
Remove `sellNXMTokens` after removing the deprecated functions.

2020-12-22 15:37 UTC, danoctavian commented on contracts/Distributor.sol
> +    uint feePercentage
i specifically log it because it's not logged anywhere

2020-12-22 15:44 UTC, danoctavian commented on contracts/DistributorFactory.sol
> +        return address(d);
yeah unlikely

2020-12-22 17:02 UTC, danoctavian commented on contracts/Distributor.sol
> +  }
can you clarify this? approve an erc20 token?

2020-12-22 17:12 UTC, danoctavian commented on contracts/Distributor.sol
> +  }
the main flow for cashing out is the sell flow as i see it, you either:

* sell (cashout on your gains)
* take it out

i argued at some point to completely get rid of sell just take it out, problem is that then the user needs another member address.

as it is now, it's the sell that seems to be the main option to cash out

2020-12-22 17:34 UTC, danoctavian commented on contracts/Distributor.sol
> +    address coverAsset
can only index up to 3 fields per solidity event

2020-12-22 17:39 UTC, danoctavian commented on contracts/Distributor.sol
> +  mapping(address => uint) public withdrawableTokens;
i like it in theory, i'll look into it a bit more see what others do. simplifies things

2020-12-22 17:41 UTC, danoctavian commented on contracts/Distributor.sol
> +  Ownable,
yes
```    /**
     * @dev Initializes the contract setting the deployer as the initial owner.
     */
    constructor () internal {
        address msgSender = _msgSender();
        _owner = msgSender;
        emit OwnershipTransferred(address(0), msgSender);
    }
    
    ```
    
    and then the factory does:
    https://github.com/NexusMutual/distributor-contract/blob/be29e21cd00fa842a61a8e648ca091f718967af6/contracts/DistributorFactory.sol#L31

2020-12-22 17:56 UTC, danoctavian commented on contracts/Distributor.sol
> +    pool = IPool(poolAddress);
then let's use for cover.sol the same, fetch it from master. if we assume the master is "forever" why one is special and the other is not probably easier like this

2020-12-22 17:58 UTC, danoctavian commented on contracts/Distributor.sol
> +  function executeCoverAction(uint tokenId, uint8 action, bytes calldata data)
will be adding solidity docs to all, once we're done with the review but yeah this needs a clear explanation

2020-12-22 18:36 UTC, danoctavian commented on contracts/Distributor.sol
> +    ) = cover.getCover(tokenId);
i took inspiration from this comment and created a function called 

function getPayoutOutcome(uint coverId, uint claimId) external view returns (bool completed, uint paidAmount, address asset);

this way we don't need getCover at all since this is all we care about really

2020-12-22 18:44 UTC, shark0der commented on contracts/Distributor.sol
> +    pool = IPool(poolAddress);
What I meant is that Cover and NXMToken won't change - we can have them fixed. The pool however will most likely change at some point! That's the only contract we should fetch from master.

2020-12-22 18:56 UTC, shark0der commented on contracts/Distributor.sol
> +  }
Yes. Basically proxy the erc20 token through this contract like we do with the ether.
For example, if we remove the deposit CN functionality that we have in place and ask cover owners to send coverAsset to be able to submit a claim. Currently this function will proxy the ETH. If we don't enable token transfer as well through this function then things get complicated because as a user you'd have to:
1. Perform the approval on the Cover contract
2. Call this contract which proxies the call to Cover
3. Cover would either have to pull the funds from tx.origin (which breaks contracts), or pull the funds from an address that's passed via the encoded `bytes calldata data`. This leads to a vulnerability though because there's no validation that the caller is actually the person owning the funds, ex.: Alice approves Distributor, Eve calls `executeCoverAction({ transferFrom: alice.address })`.

2020-12-23 05:51 UTC, danoctavian commented on contracts/Distributor.sol
> +  }
we could pass msg.sender of the distributor call as a param into the executeAction of Cover.sol

that would be a "secure" tx.origin

2020-12-23 06:31 UTC, danoctavian commented on contracts/Distributor.sol
> +  mapping(address => uint) public withdrawableTokens;
in terms of failure, having the treasury doesn't change things, since the buyCover function can be disabled by Owner.

If Owner sets a bad treasury address where say ETH transfers fail, it's equivalent to setting allowBuys = false

Security is potentially for the user supplied wallet since they have flexibility.

i'd wonder here as well in terms of user experience, what is easier. While not having a treasury wallet means you don't need to have one at setup time (easier to start), it makes cashing out the funds an explicit action that you need to do once in a while.

2020-12-23 10:18 UTC, shark0der commented on contracts/Distributor.sol
> +  fallback () payable external {
Replace with receive

2020-12-23 10:19 UTC, shark0der commented on contracts/DistributorFactory.sol
> +    INXMaster master;
Make immutable

2020-12-23 10:20 UTC, shark0der commented on contracts/DistributorFactory.sol
> +    address coverAddress;
Unused?

2021-02-04 13:12 UTC, shark0der commented on contracts/Distributor.sol
> +      token.approve(address(cover), coverPrice);
Use `token.safeApprove` since we don't know what other asset we might be using in the future

2021-02-04 13:30 UTC, shark0der commented on contracts/Distributor.sol
> +    if (assetAmount > 0) {
Change the condition and add the return here:
```
if (assetAmount == 0) {
  return cover.executeCoverAction(tokenId, action, data);
}
```

This will remove an indent level for the rest of this function's code

2021-02-04 13:51 UTC, shark0der commented on contracts/Distributor.sol
> +        uint remainder = assetAmount.sub(withheldAmount);
You never validated that `assetAmount == msg.value`.

2021-02-04 13:53 UTC, danoctavian commented on contracts/Distributor.sol
> +        uint remainder = assetAmount.sub(withheldAmount);
👏

2021-02-04 13:56 UTC, shark0der commented on contracts/Distributor.sol
> +        uint remainder = assetAmount.sub(withheldAmount);
You never validated that `assetAmount == msg.value`.

2021-02-04 13:59 UTC, shark0der commented on contracts/Distributor.sol
> +        (bool ok, /* data */) = address(msg.sender).call{value: remainder}("");
Let's make this call only if `remainder > 0`

2021-02-04 14:27 UTC, shark0der commented on deploy/deploy-distributor.js
> +    },
We probably should skip prompting the factory address and fill it in automatically if the network is kovan/mainnet.
Will need to write them in an object at the top of this file `const factories = { mainnet: '0x...', kovan: '0x...' };`

2021-02-04 14:30 UTC, shark0der commented on test-environment.config.js
> +module.exports = {
Remove this file.

2021-02-04 14:31 UTC, shark0der commented on package.json
> +    "@uniswap/lib": "^4.0.0-alpha",
Remove `@uniswap/lib`

2021-02-05 05:24 UTC, danoctavian commented on contracts/Distributor.sol
> +      token.approve(address(cover), coverPrice);
safeApprove has this extra require
```    function safeApprove(IERC20 token, address spender, uint256 value) internal {
        // safeApprove should only be called when setting an initial allowance,
        // or when resetting it to zero. To increase and decrease it, use
        // 'safeIncreaseAllowance' and 'safeDecreaseAllowance'
        // solhint-disable-next-line max-line-length
        require((value == 0) || (token.allowance(address(this), spender) == 0),
            "SafeERC20: approve from non-zero to non-zero allowance"
        );
        _callOptionalReturn(token, abi.encodeWithSelector(token.approve.selector, spender, value));
    }```
    
    which disallows `SafeERC20: approve from non-zero to non-zero allowance` i found this too restrictive and breaks the current logic

2021-02-10 07:44 UTC, danoctavian commented on package.json
> +    "@uniswap/lib": "^4.0.0-alpha",
doesn't compile anymore if i remove it, will leave it here for now

2021-04-27 12:54 UTC, danoctavian approved these changes
LGTM

2021-04-27 12:54 UTC, merged